// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XanhNow.Auth.Login.Infrastructure.Persistence;

#nullable disable

namespace XanhNow.Auth.Login.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260710040733_InitialAuthLoginSchema")]
    partial class InitialAuthLoginSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XanhNow.Auth.Login.Infrastructure.Persistence.AuthAuditLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("IpHash")
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PhoneNumberMasked")
                        .HasColumnType("text")
                        .HasColumnName("phone_number_masked");

                    b.Property<string>("SessionIdHash")
                        .HasColumnType("text")
                        .HasColumnName("session_id_hash");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_auth_audit_logs_correlation_id");

                    b.ToTable("auth_audit_logs", "auth");
                });

            modelBuilder.Entity("XanhNow.Auth.Login.Infrastructure.Persistence.LoginAttemptRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientInfoHash")
                        .HasColumnType("text")
                        .HasColumnName("client_info_hash");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason_code");

                    b.Property<string>("IpHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_hash");

                    b.Property<string>("PhoneNumberHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number_hash");

                    b.Property<string>("PhoneNumberMasked")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number_masked");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_attempts");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_login_attempts_created_at");

                    b.ToTable("login_attempts", "auth");
                });

            modelBuilder.Entity("XanhNow.Auth.Login.Infrastructure.Persistence.OutboxEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("EventId")
                        .HasName("pk_outbox_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_outbox_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_created_at");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_outbox_status_available_at");

                    b.ToTable("outbox_events", "auth");
                });

            modelBuilder.Entity("XanhNow.Auth.Login.Infrastructure.Persistence.UserPhoneHistoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("NewPhoneNumberHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_phone_number_hash");

                    b.Property<string>("NewPhoneNumberMasked")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_phone_number_masked");

                    b.Property<string>("OldPhoneNumberHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_phone_number_hash");

                    b.Property<string>("OldPhoneNumberMasked")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("old_phone_number_masked");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_phone_histories");

                    b.HasIndex("UserId");

                    b.ToTable("user_phone_histories", "auth");
                });

            modelBuilder.Entity("XanhNow.Auth.Login.Infrastructure.Persistence.UserRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordAlgorithm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_algorithm");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordPepperVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_pepper_version");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhoneNumberMasked")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number_masked");

                    b.Property<string>("PhoneNumberNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number_normalized");


                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("LastLoginAt")
                        .HasDatabaseName("ix_users_last_login_at");

                    b.HasIndex("PhoneNumberNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_users_phone_number_normalized");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("XanhNow.Auth.Login.Infrastructure.Persistence.UserPhoneHistoryRecord", b =>
                {
                    b.HasOne("XanhNow.Auth.Login.Infrastructure.Persistence.UserRecord", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
